[workspace]
authors = ["GavinJ738 <gavinjohnson2004@gmail.com>"]
channels = ["conda-forge"]
name = "moveit_msgs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = ">=0.57.2,<0.58"
